name: Create Release

on:
  push:
    branches:
      - master # 监听 master 分支的 push 事件

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # 使用适当的 Node.js 版本

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build # 替换为你的构建命令，例如 `npm run build`

      - name: Create ZIP of dist
        run: zip -r dist.zip dist # 将 dist 目录打包为 dist.zip

      - name: Create a new Git tag
        id: tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 用于创建 GitHub Release
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: Release ${{ env.VERSION }}
          body: |
            Release notes for version ${{ env.VERSION }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
