name: Create Release

on:
  push:
    branches:
      - master # 监听 master 分支的 push 事件

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14" # 使用适当的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # 替换为你的构建命令，例如 `npm run build`

      - name: Create a new Git tag
        id: tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 用于创建 GitHub Release
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: Release ${{ env.VERSION }}
          body: |
            Release notes for version ${{ env.VERSION }}

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./dist/*
          asset_name: dist.zip
          asset_content_type: application/zip
